### ISSUE TITLE
Doesn't work for MCPE Players

### ISSUE THREAD

**Issue by OfficialLilKev** [Shelly7w7/VoucherPlus#1] opened 2018-11-22 21:08 UTC
The plugin doesn't work on MCPE

**Comment by OfficialLilKev** [comment] 2018-11-22 21:08
Only works for Windows 10 Players

**Comment by Shelly7w7** [comment] 2018-11-24 09:16
I'm pretty sure, in New update, you need to tap/hold in air for a longer amount of time.

**Comment by Shelly7w7** [comment] 2018-11-24 09:18
It works for me, can you reproduce it?

**Comment by Shelly7w7** [comment] 2019-04-23 20:14
Never received a reply, closing.

**Closed as completed by Shelly7w7** 2019-04-23 20:14 UTC
Labels: Unconfirmed
